### ISSUE TITLE
Unreal Engine 4 packaging error

### ISSUE THREAD

**Issue by dgs3d** [getnamo/leap-ue4#19]
Hi, i´m having an ´UNKNOWN ERROR´ when I try to package a Game with the official LeapmotionPlugin. If i disable the plug In, I don´t get that error. 
Anybody has that issue?
[outputLog.txt](https://github.com/getnamo/leap-ue4/files/761874/outputLog.txt)

**Comment by dgs3d** [comment]
LogWindows: LaunchURL https://github.com/getnamo/leap-ue4
LogDirectoryWatcher: A directory notification for '../../../Engine/Plugins/' was aborted.
UATHelper: Packaging (Windows (64-bit)): Running AutomationTool...
UATHelper: Packaging (Windows (64-bit)): Automation.ParseCommandLine: Parsing command line: -ScriptsForProject="D:/DOCUMENTS/Unreal Projects/house_2 - Copy/house_2.uproject" BuildCookRun -nocompile -nocompileeditor -installed -nop4 -project="D:/DOCUMENTS/Unreal Projects/house_2 - Copy/house_2.uproject" -cook -stage -archive -archivedirectory=C:/Users/admin/D
esktop -package -clientconfig=Development -ue4exe=UE4Editor-Cmd.exe -pak -prereqs -nodebuginfo -targetplatform=Win64 -build -CrashReporter -utf8output
UATHelper: Packaging (Windows (64-bit)): Automation.Process: Setting up command environment.
UATHelper: Packaging (Windows (64-bit)): BuildCookRun.SetupParams: Setting up ProjectParams for D:\DOCUMENTS\Unreal Projects\house_2 - Copy\house_2.uproject
UATHelper: Packaging (Windows (64-bit)): Project.Build: ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: D:\PROGRAMS\3D\Epic Games\4.14\Engine\Binaries\DotNET\UnrealBuildTool.exe house_2 Win64 Development -Project="D:\DOCUMENTS\Unreal Projects\house_2 - Copy\house_2.uproject"  "D:\DOCUMENTS\Unreal Projects\house_2 - Copy\house_2.uproject"  -remoteini="D:\DOCUMENTS\Unreal Projects\house_2 - Copy" -n
oxge -generatemanifest -NoHotReload
UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: Took 1.0530602s to run UnrealBuildTool.exe, ExitCode=0
UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: D:\PROGRAMS\3D\Epic Games\4.14\Engine\Binaries\DotNET\UnrealBuildTool.exe house_2 Win64 Development -Project="D:\DOCUMENTS\Unreal Projects\house_2 - Copy\house_2.uproject"  "D:\DOCUMENTS\Unreal Projects\house_2 - Copy\house_2.uproject"  -remoteini="D:\DOCUMENTS\Unreal Projects\house_2 - Copy" -n
oxge -NoHotReload -ignorejunk
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: Creating makefile for house_2 (no existing makefile)
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: Performing full C++ include scan (no include cache file)
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: ERROR: Windows SDK v8.1 must be installed in order to build this target.
UATHelper: Packaging (Windows (64-bit)): CommandUtils.Run: Run: Took 2.8721643s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (Windows (64-bit)): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): D:\PROGRAMS\3D\Epic Games\4.14\Engine\Binaries\DotNET\UnrealBuildTool.exe house_2 Win64 Development -Project="D:\DOCUMENTS\Unreal Projects\house_2 - Copy\house_2.uproject"  "D:\
DOCUMENTS\Unreal Projects\house_2 - Copy\house_2.uproject"  -remoteini="D:\DOCUMENTS\Unreal Projects\house_2 - Copy" -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2017.02.08-17.34.08.txt' 
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunAndLog(CommandEnvironment Env, String App, String CommandLine, String LogName, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, FileReference Project, String Target, String Platform, String Config, String AdditionalArgs, String LogName, Dictionary`2 EnvVars)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.BuildWithUBT(String TargetName, UnrealTargetPlatform TargetPlatform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictio
nary`2 InTargetToManifest)
UATHelper: Packaging (Windows (64-bit)):    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask)
UATHelper: Packaging (Windows (64-bit)):    at BuildCookRun.DoBuildCookRun(ProjectParams Params)
UATHelper: Packaging (Windows (64-bit)):    at BuildCookRun.ExecuteBuild()
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.BuildCommand.Execute()
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Automation.Process(String[] Arguments)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Program.MainProc(Object Param)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param)
UATHelper: Packaging (Windows (64-bit)):    at AutomationTool.Program.Main()
UATHelper: Packaging (Windows (64-bit)): Program.Main: AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults:Error: Error Unknown Error

**Comment by getnamo** [comment]
from your log it says: UnrealBuildTool: ERROR: Windows SDK v8.1 must be installed in order to build this target. any idea why it would say that?

see https://answers.unrealengine.com/questions/81234/generate-project-files-error.html

**Comment by getnamo** [comment]
should be addressed in the modern re-write

**Comment by GybelsTristan** [comment]
I have it installed, not working
