### ISSUE TITLE
Unreal UE4 version 4.15 and LEAP Motion Crashing when Running Standalone Game

### ISSUE THREAD

**Issue by KBlackford** [getnamo/leap-ue4#21]
When I enable the LEAP Plugin and Add it to a UE4 4.15 Project and Launch it as a Standalone game,
 I get this error.

 I do not get an Error if I run it in Preview Mode. Only when I try to Build the Deployable Game.

 I have tried this on multiple computers.
 I have started with Blank Projects.
 As Soon as I add a Leap Enabled Character, even the Default ones with the Plugin, I can no longer Build a Windows Deployable Standalone using the Launch Button in UE4 4.15

If I remove leap enabled pawn from the Default Pawn Class setting in the Game Mode.  It will compile.

 This works fine in UE4 4.14

 Please help!
 This is Killing my Project right now.

 I have included all errors I can Find.

I posted here as well
https://forums.unrealengine.com/showthread.php?49107-Plugin-Leap-Motion-Event-Driven/page13

 Ken

 Assertion failed: LocalExportIndex.IsNull() [File:D:\Build\++UE4+Release-4.15+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp] [Line: 1915] 

 0x000000004D287788
 0x00000000A33F4000
 0x0000000000000400
 0x00000000062CAD70
 0x00000000CFDD3568
 0x0000000000000001
 0x0000000000000001

 LogPlayLevel: CommandUtils.Run: Run: C:\Kenneth\Documents\Unreal Projects\BMW5\Saved\StagedBuilds\WindowsNoEditor\BMW5\Binaries\Win64\BMW5.exe ../../../BMW5/BMW5.uproject /Game/AIUE_V02_003/Maps/AIUE_V02_003 -stdout -abslog="C:\Users\Kenneth\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.15\Client.log" -Messaging -nomcp -Wi
 ndowed -CrashForUAT -SessionId=3E7D2C9F465D984DE1AD8BA0358D90E4 -SessionOwner="Kenneth" -SessionName="Launch On Device"
 LogPlayLevel: BMW5:
 OCULUS: Info: [HMDState] Requested to SetForegroundWindow(111326ll)
 LogPlayLevel: BMW5: LogInit:Display: Running engine for game: BMW5
 LogPlayLevel: BMW5: LogInit:Display: RandInit(-1899815146) SRandInit(-1899815146).LogStreaming:Display: Async Loading initialized: New Async IO: true, Event Driven Loader: true, Async Loading Thread: false
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: LogStreaming:Display: Async Loading initialized: New Async IO: true, Event Driven Loader: true, Async Loading Thread: falseLogBlueprintUserMessages:Warning: DEBUG: LocalNotification DefaultPlatformService NOT FOUND
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.00:652][ 0]LogBlueprintUserMessages:Warning: DEBUG: LocalNotification DefaultPlatformService NOT FOUNDLogConsoleManager:Warning: Setting the console variable 'r.VSync' with 'SetByGameSetting' was ignored as it is lower priority than the previous 'SetByCode'. Value remains '0'
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.03:869][ 0]LogConsoleManager:Warning: Setting the console variable 'r.VSync' with 'SetByGameSetting' was ignored as it is lower priority than the previous 'SetByCode'. Value remains '0'LogInit:Display: Game Engine Initialized.
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.03:879][ 0]LogInit:Display: Game Engine Initialized.LogInit:Display: Starting Game.
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.03:880][ 0]LogInit:Display: Starting Game.LogWindows:Warning: CreateProc failed (2) ../../../Engine/Binaries/Win64/CrashReportClient.exe "C:/Kenneth/Documents/Unreal Projects/BMW5/Saved/StagedBuilds/WindowsNoEditor/BMW5/Saved/Logs/UE4CC-Windows-8697A35649235C9EED3F35AEFCF72A0A_0000" -AppName=UE4-BMW5 -CrashGUID=UE4CC-Wi
 ndows-8697A35649235C9EED3F35AEFCF72A0A_0000 -DebugSymbols=......\Engine\Intermediate\Symbols
 LogPlayLevel: BMW5: LogWindows:Error: begin: stack for UAT
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Warning: CreateProc failed (2) ../../../Engine/Binaries/Win64/CrashReportClient.exe "C:/Kenneth/Documents/Unreal Projects/BMW5/Saved/StagedBuilds/WindowsNoEditor/BMW5/Saved/Logs/UE4CC-Windows-8697A35649235C9EED3F35AEFCF72A0A_0000" -AppName=UE4-BMW5 -CrashGUID=UE4CC-Windows-8697A35649235C9EED3F35AEF
 CF72A0A_0000 -DebugSymbols=......\Engine\Intermediate\Symbols
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: begin: stack for UATLogWindows:Error: === Critical error: ===
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: === Critical error: ===LogWindows:Error:
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: LogWindows:Error: Assertion failed: LocalExportIndex.IsNull() [File:D:\Build\++UE4+Release-4.15+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp] [Line: 1915]
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: Assertion failed: LocalExportIndex.IsNull() [File:D:\Build\++UE4+Release-4.15+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp] [Line: 1915] LogWindows:Error:
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: LogWindows:Error:
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: LogWindows:Error:
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: LogWindows:Error: 0x000000004D287788
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: 0x000000004D287788LogWindows:Error: 0x00000000A33F4000
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: 0x00000000A33F4000LogWindows:Error: 0x0000000000000400
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: 0x0000000000000400LogWindows:Error: 0x00000000062CAD70
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: 0x00000000062CAD70LogWindows:Error: 0x00000000CFDD3568
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: 0x00000000CFDD3568LogWindows:Error: 0x0000000000000001
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: 0x0000000000000001LogWindows:Error: 0x0000000000000001
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: 0x0000000000000001LogWindows:Error:
 LogPlayLevel: BMW5:
 LogPlayLevel: BMW5: [2017.02.22-04.39.21:780][ 0]LogWindows:Error: LogWindows:Error: end: stack for UAT
 LogPlayLevel: BMW5:
 LogPlayLevel: Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.AutomationException: Client exited with error code: 3
 LogPlayLevel: at Project.RunStandaloneClient(List1 DeployContextList, String ClientLogFile, ERunOptions ClientRunFlags, String ClientApp, String ClientCmdLine, ProjectParams Params)
 LogPlayLevel: at Project.RunInternal(ProjectParams Params, String ServerLogFile, String ClientLogFile)
 LogPlayLevel: at Project.Run(ProjectParams Params)
 LogPlayLevel: at BuildCookRun.DoBuildCookRun(ProjectParams Params)
 LogPlayLevel: at BuildCookRun.ExecuteBuild()
 LogPlayLevel: at AutomationTool.BuildCommand.Execute()
 LogPlayLevel: at AutomationTool.Automation.Execute(List1 CommandsToExecute, CaselessDictionary1 Commands)
 LogPlayLevel: at AutomationTool.Automation.Process(String[] Arguments)
 LogPlayLevel: at AutomationTool.Program.MainProc(Object Param)
 LogPlayLevel: at AutomationTool.InternalUtils.RunSingleInstance(Func2 Main, Object Param)
 LogPlayLevel: at AutomationTool.Program.Main()
 LogPlayLevel: Program.Main: AutomationTool exiting with ExitCode=1 (Error_Unknown)
 LogPlayLevel: Completed Launch On Stage: Run Task, Time: 28.035717
 LogPlayLevel: BUILD FAILED
 PackagingResults:Error: Error Launch failed! Unknown Error

**Comment by KBlackford** [comment]
![screenshot 2017-02-21 20 39 17](https://cloud.githubusercontent.com/assets/8919875/23283916/7a5efabc-f9dd-11e6-8fa1-e7e7d28c5c93.png)

**Comment by KBlackford** [comment]
ok. I Downloaded, installed the Source Code Ran The Editor and launched the game.

Here is the last part where it breaks.
[2017.02.24-09.20.23:992][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:791][  0]LogStreaming:Display: Loading: DefaultSceneRoot_GEN_VARIABLE in /LeapMotion/Blueprints/Rigging/FloatingHands/LeapHandsActorBaseLogStreaming:Display: Loading: LeapHMDOffset_GEN_VARIABLE in /LeapMotion/Blueprints/Rigging/FloatingHands/LeapHandsActorBase
[2017.02.24-09.20.23:994][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.23:994][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:791][  0]LogStreaming:Display: Loading: LeapHMDOffset_GEN_VARIABLE in /LeapMotion/Blueprints/Rigging/FloatingHands/LeapHandsActorBaseLogStreaming:Display: Loading: DefaultSceneRoot_GEN_VARIABLE in /LeapMotion/Blueprints/Rigging/FloatingHands/LeapRiggedEchoHandsActor
[2017.02.24-09.20.23:996][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.23:996][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:791][  0]LogStreaming:Display: Loading: DefaultSceneRoot_GEN_VARIABLE in /LeapMotion/Blueprints/Rigging/FloatingHands/LeapRiggedEchoHandsActorLogStreaming:Display: Loading: LeftHandMesh_GEN_VARIABLE in /LeapMotion/Blueprints/Rigging/FloatingHands/LeapRiggedEchoHandsActor
[2017.02.24-09.20.23:998][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.23:998][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:791][  0]LogStreaming:Display: Loading: LeftHandMesh_GEN_VARIABLE in /LeapMotion/Blueprints/Rigging/FloatingHands/LeapRiggedEchoHandsActorLogStreaming:Display: Loading: RightHandMesh_GEN_VARIABLE in /LeapMotion/Blueprints/Rigging/FloatingHands/LeapRiggedEchoHandsActor
[2017.02.24-09.20.23:999][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.23:999][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:792][  0]LogStreaming:Display: Loading: RightHandMesh_GEN_VARIABLE in /LeapMotion/Blueprints/Rigging/FloatingHands/LeapRiggedEchoHandsActorLogStreaming:Display: Loading: AnimBody_0 in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:000][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:000][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:802][  0]LogStreaming:Display: Loading: AnimBody_0 in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Head in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:001][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:002][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:802][  0]LogStreaming:Display: Loading: Head in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:003][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:003][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:802][  0]LogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:004][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:005][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:802][  0]LogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:006][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:006][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:802][  0]LogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:008][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:009][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:802][  0]LogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:011][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:011][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:802][  0]LogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:012][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:013][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:803][  0]LogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:014][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:014][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:803][  0]LogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:015][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:015][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:803][  0]LogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:016][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:016][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:803][  0]LogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnector
[2017.02.24-09.20.24:017][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:017][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:803][  0]LogStreaming:Display: Loading: Distal in /LeapMotion/Blueprints/LeapConnectors/LeapAnimBodyConnectorLogWindows:Error: begin: stack for UAT
[2017.02.24-09.20.24:018][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:018][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:814][  0]LogWindows:Error: begin: stack for UATLogWindows:Error: === Critical error: ===
[2017.02.24-09.20.24:019][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:019][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:814][  0]LogWindows:Error: === Critical error: ===LogWindows:Error:
[2017.02.24-09.20.24:021][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:022][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:814][  0]LogWindows:Error: LogWindows:Error: Assertion failed: LocalExportIndex.IsNull() [File:C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp] [Line: 1917]
[2017.02.24-09.20.24:023][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:024][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:814][  0]LogWindows:Error: Assertion failed: LocalExportIndex.IsNull() [File:C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp] [Line: 1917] LogWindows:Error:
[2017.02.24-09.20.24:025][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:025][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:814][  0]LogWindows:Error: LogWindows:Error:
[2017.02.24-09.20.24:026][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:026][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:814][  0]LogWindows:Error: LogWindows:Error:
[2017.02.24-09.20.24:026][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:027][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:814][  0]LogWindows:Error: LogWindows:Error:
[2017.02.24-09.20.24:027][361]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:027][361]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:814][  0]LogWindows:Error: LogWindows:Error: end: stack for UAT
[2017.02.24-09.20.24:144][362]LogPlayLevel: leaptest1-Win64-Debug:
[2017.02.24-09.20.24:145][362]LogPlayLevel: Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.AutomationException: Client exited with error code: 3
[2017.02.24-09.20.24:146][362]LogPlayLevel:    at Project.RunStandaloneClient(List`1 DeployContextList, String ClientLogFile, ERunOptions ClientRunFlags, String ClientApp, String ClientCmdLine, ProjectParams Params) in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\Scripts\RunProjectCommand.Automation.cs:line 379
[2017.02.24-09.20.24:147][362]LogPlayLevel:    at Project.RunInternal(ProjectParams Params, String ServerLogFile, String ClientLogFile) in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\Scripts\RunProjectCommand.Automation.cs:line 177
[2017.02.24-09.20.24:148][362]LogPlayLevel:    at Project.Run(ProjectParams Params) in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\Scripts\RunProjectCommand.Automation.cs:line 114
[2017.02.24-09.20.24:149][362]LogPlayLevel:    at BuildCookRun.DoBuildCookRun(ProjectParams Params) in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 244
[2017.02.24-09.20.24:149][362]LogPlayLevel:    at BuildCookRun.ExecuteBuild() in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 43
[2017.02.24-09.20.24:150][362]LogPlayLevel:    at AutomationTool.BuildCommand.Execute() in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 100
[2017.02.24-09.20.24:151][362]LogPlayLevel:    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands) in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 561
[2017.02.24-09.20.24:152][362]LogPlayLevel:    at AutomationTool.Automation.Process(String[] Arguments) in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 531
[2017.02.24-09.20.24:152][362]LogPlayLevel:    at AutomationTool.Program.MainProc(Object Param) in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:line 135
[2017.02.24-09.20.24:153][362]LogPlayLevel:    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param) in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\AutomationUtils\Utils.cs:line 704
[2017.02.24-09.20.24:154][362]LogPlayLevel:    at AutomationTool.Program.Main() in C:\Projects\PVR\GitHub\UnrealEngine\Engine\Source\Programs\AutomationTool\Program.cs:line 59
[2017.02.24-09.20.24:155][362]LogPlayLevel: leaptest1-Win64-Debug: [2017.02.24-09.20.23:814][  0]LogWindows:Error: end: stack for UAT
[2017.02.24-09.20.24:155][362]OCULUS: Info: [HMDState] Requested to SetForegroundWindow(4b185cll)
[2017.02.24-09.20.24:471][363]LogPlayLevel: Program.Main: AutomationTool exiting with ExitCode=1 (Error_Unknown)
[2017.02.24-09.20.24:472][363]LogPlayLevel: Completed Launch On Stage: Run Task, Time: 7.509249
[2017.02.24-09.20.24:473][363]LogPlayLevel: BUILD FAILED
[leaptest1.txt](https://github.com/getnamo/leap-ue4/files/798829/leaptest1.txt)

**Comment by KBlackford** [comment]
BTW I added this line to log more info to find what the cause is.
Line 1902 in AsyncLoading.cpp
UE_CLOG(true, LogStreaming, Display, TEXT("Loading: %s in %s"), *Import.ObjectName.ToString(), *ImportPackage->GetName());
